// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jodcjkpzutlxbswtkvbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpvZGNqa3B6dXRseGJzd3RrdmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NjEzNjksImV4cCI6MjA2MTUzNzM2OX0.AdTnUNth2LaGORlCOXJnt-NvseELuXik0HuL1YRVbj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);